FROM node:22-alpine

WORKDIR /app

# Install build dependencies for native modules
RUN apk add --no-cache python3 make g++

# Install pnpm
RUN npm install -g pnpm

COPY . .

RUN pnpm install

# Set environment variable to disable ESLint
ENV NEXT_DISABLE_ESLINT=true
RUN pnpm run build --filter=web

# Expose Next.js default port
EXPOSE 3000

# Start the app
CMD ["pnpm", "--filter", "web", "start"]